### ISSUE TITLE
Potential issue with log of negative numbers

### ISSUE THREAD

**Issue by AnglerCreel** [stan-dev/loo#101]
In the following function of Loo called from mcse_elpd_loo <- mcse_elpd(ll, elpd_loo, psis_object), **var(log(z))** can generate NaN because of possible negative values of z.

```r
#################################################
function (ll, E_elpd, psis_object, n_samples = 1000) 
{
  E_epd <- exp(E_elpd)
  w <- weights(psis_object, log = FALSE)
  r_eff <- attr(psis_object, "r_eff")
  var_elpd <- sapply(seq_len(ncol(w)), function(i) {
    var_epd_i <- sum(w[, i]^2 * (exp(ll[, i]) - E_epd[i])^2)
    sd_epd_i <- sqrt(var_epd_i)
    z <- rnorm(n_samples, mean = E_epd[i], sd = sd_epd_i)
    var(log(z))
  })
  sqrt(var_elpd/r_eff)
}
```

**Comment by avehtari** [comment]
Thanks for opening the issue. Do you have an example where this happens? I'm interest because I had assumed that would be very unlikely and if you have found a counter example there is probably something to learn from that

**Comment by AnglerCreel** [comment]
I have a Stan model that uses GP to model some multiple time series data (T year and S sites). I generate point-wise log_lik for the observed data like this: 
      log_lik[n] = normal_lpdf(y[n] | y_hat[n], sigma_error_site_2);

For the log_lik values list below, I got: 
>
Warning messages:
1: Some Pareto k diagnostic values are too high. See help('pareto-k-diagnostic') for details.
2: In log(z) : NaNs produced

[loo_mcse_elpd_loo_neg_logz.R.txt](https://github.com/stan-dev/loo/files/2971665/loo_mcse_elpd_loo_neg_logz.R.txt)

**Comment by avehtari** [comment]
fixed

**Comment by avehtari** [comment]
Thanks. As I guessed it's a case where PSIS fails anyway. I fixed it so that it doesn't warn about NaN's, but it will not help with too high variability in the log_lik values.
