### ISSUE TITLE
`loo` fails when `r_eff` is negative

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/loo#104]
When `do_psis` calls `n_pareto` at

https://github.com/stan-dev/loo/blob/3e8754afe580f83d0f56045bdad3da758f3198af/R/psis.R#L235

the result can be `NaN` when `r_eff` is negative due to the square root in

https://github.com/stan-dev/loo/blob/3e8754afe580f83d0f56045bdad3da758f3198af/R/psis.R#L370

in which case `throw_tail_length_warnings` fails.

The negative `r_eff` can be triggered by
```
library(rstanarm)
d.AD <- data.frame(treatment = gl(3,3), outcome =  gl(3,1,9),
                   counts = c(18,17,15,20,10,20,25,13,12))

fit_pois <- stan_glm(counts ~ outcome + treatment, data = d.AD,
                        family = poisson, chains = 2, iter = 40,
                        seed = 12345, refresh = 0)
```

**Comment by jgabry** [comment]
I assume this is due to the new effective sample size calculations in RStan? @avehtari What do you think we should do in this case? Set any negative `r_eff` to 0? Maybe throw a warning too since that's an alarmingly bad effective sample size.

**Comment by avehtari** [comment]
I copied the updated ess_rfun code from rstan develop (and commit and push) and now this works
```
Pareto k diagnostic values:
                         Count Pct.    Min. n_eff
(-Inf, 0.5]   (good)     2     22.2%   22        
 (0.5, 0.7]   (ok)       2     22.2%   5         
   (0.7, 1]   (bad)      5     55.6%   12        
   (1, Inf)   (very bad) 0      0.0%   <NA>      
See help('pareto-k-diagnostic') for details.
```

**Comment by bgoodri** [comment]
OK, we may need to do a loo release.
