### ISSUE TITLE
compare output different for 2 models vs more than 2 models.

### ISSUE THREAD

**Issue by rpruim** [stan-dev/loo#107]
Is there a reason why compare has a different output format (and less information) when comparing 2 models than when comparing > 2 models?

```r
> compare(loo(fert1_brm), loo(fert2_brm), loo(fert4_brm))

               elpd_diff se_diff elpd_loo p_loo  looic 
loo(fert4_brm)    0.0       0.0  -334.8     34.2  669.6
loo(fert2_brm)  -61.7       7.6  -396.5      9.2  793.0
loo(fert1_brm)  -63.1       8.0  -397.9      5.6  795.8

> compare(loo(fert1_brm), loo(fert2_brm))

elpd_diff        se 
      1.4       3.7 
```

**Comment by paul-buerkner** [comment]
This has been changed in the latest `loo` version from CRAN in which you should now use `loo_compare`

**Comment by rpruim** [comment]
Thanks for the info.  Is there an ETA for CRAN release?

**Comment by rpruim** [comment]
Looks like `loo_compare()` gives a terser summary.

```
          elpd_diff se_diff
fert4_brm   0.0       0.0  
fert2_brm -61.2       7.7  
fert1_brm -62.6       8.1 
```

Will there still be a way to get the expanded summary in a table form?

```
          elpd_diff se_diff elpd_loo p_loo  looic 
fert4_loo    0.0       0.0  -335.3     34.7  670.5
fert2_loo  -61.2       7.7  -396.5      9.2  793.0
fert1_loo  -62.6       8.1  -397.9      5.6  795.8
```

**Comment by jgabry** [comment]
Hi Randall, glad to see you're using `loo`! 

The `loo_compare()` function is already included in the latest CRAN release (version 2.1.0). Getting the expanded summary is still possible like this:

```r
comp <- loo_compare(...)
print(comp) # simplified output
print(comp, simplify = FALSE) # full table
```

The object `comp` is just a matrix storing the estimates with a special class in order to implement the print method. 

Hope that helps!

Jonah

**Comment by rpruim** [comment]
Thanks for the clarification.  I thought it was new in github and not yet on CRAN.

Some of my students were asking about the different output formats for 2 vs >2 variables when using `compare()`.  I'll let them know about `loo_compare()` and the options to its print method.

**Comment by jgabry** [comment]
Sounds good. Thanks!

**Comment by rpruim** [comment]
Would it make sense to add the `simplify` argument to `loo_compare()`, store the value as an attribute to the object it creates, and then read that value when executing `print()`?  That way one could just do

```
loo_compare(..., simplify = FALSE)
```

Also, this option would show up in the documentation for `loo_compare()`, making it much easier for users to discover/recall.

**Comment by jgabry** [comment]
Thanks for the suggestion. Yes that's a possibly. At a minimum we can add something towards the top of the documentation for `loo_compare` mentioning the print method with `simplify`.

**Comment by jgabry** [comment]
Just updated the doc in https://github.com/stan-dev/loo/commit/506497a1d4db510dd329a5e6190bb1a6d24bd964 to mention the print method and `simplify` argument more prominently.
