### ISSUE TITLE
Incomplete documentation for psis function

### ISSUE THREAD

**Issue by dpsimpson** [stan-dev/loo#112]
This came up when I was trying to use the `weights.psis` function to actually make an importance sampler. The weights that are returned are _not_ the log-PSIS weights, but rather the log-PSIS weights _minus_ the largest log ratio.  @avehtari documented the solution here. https://discourse.mc-stan.org/t/trouble-using-loo-psis-for-importance-sampling/9209/2

This is not super urgent, but it would be convenient to have it clarified in a future version.  Also possibly to have a simple vignette that shows how to implement an importance sampler.  I'm happy to volunteer to do these things (but not in the next week or so).

**Comment by avehtari** [comment]
To further clarify the log-PSIS weights (non-translated ones) are useful if
1) if normalization terms are known and regular importance sampling (non-self-normalized) is used
2) if normalization terms are unknown and need to estimate the ratio of normalization terms (e.g. one of the normalization terms is known, and then we want to infer the other one)

In PSIS-LOO and in most other self-normalized importance sampling, we don't need these and it was easier to leave the non-normalized weights as they are now. I now think that we could add back that largest log ratio, although then we need to check that we are not exponentiating those log-PSIS weights before subtracting the max log weight.

**Comment by jgabry** [comment]
Closing since #146 was merged
