### ISSUE TITLE
need to evaluate Rhat and n_eff for observation-wise log_lik vector?

### ISSUE THREAD

**Issue by jpritikin** [stan-dev/loo#114]
Should users be checking the Rhat and n_eff diagnostics for the log_lik vector that contains per-observation likelihoods?

**Comment by avehtari** [comment]
loo does compute n_eff's combining MCMC and IS. See Section 2.2 in https://arxiv.org/abs/1507.02646 for MCSE estimate which is part of n_eff computation. The default output shows the minimum n_eff's for different khat ranges. n_eff is often sufficient and Rhat is not necessarily needed, although in case of small n_eff Rhat can provide further information.

For more details, please ask more in Stan discourse https://discourse.mc-stan.org
