### ISSUE TITLE
kfold-generic should also say that the estimates matrix MUST have rownames

### ISSUE THREAD

**Issue by bnicenboim** [stan-dev/loo#120]
The help says
"estimates": a 1x2 matrix with column names "Estimate" and "SE" containing the ELPD estimate and its standard error.

without naming its row "elpd_kfold", `loo_compare` won't work.

I can add it to the help doc, but I wasn't sure in which branch I should do a pull request

**Comment by jgabry** [comment]
Thanks @bnicenboim! I just added this to the doc in 637a6ee, but next tme if you want to fix and submit a PR when you notice something like this that would be great! In terms of branches, you can just make a change in your fork/clone of the repo and submit a PR against the loo master branch from your version.
