### ISSUE TITLE
loo_approximate_posterior error in new vignette

### ISSUE THREAD

**Issue by jgabry** [stan-dev/loo#122]
@MansMeg @avehtari I just pushed a lot of edits to the new vignette you created (I like the vignette a lot), but I noticed a problem with the laplace approximation section. If you run it in R

https://github.com/stan-dev/loo/blob/2e363a915f8c7de0f75babb61d87337d936e7f3e/vignettes/loo2-large-data.Rmd#L265-L271

then for me `log_p` and `log_g` both come out as 3-element vectors containing `NA` only. So there are three problems:

1) log_p and log_g are length 3 (should be much longer)
2) log_p and log_g are both full of NAs (shouldn't be NA)
3) The call to `loo_approximate_posterior()` errors because of problems 1 and 2

@avehtari Are the issues with log_p and log_g related to changes in rstan::optimizing that you or @bgoodri made?

@MansMeg @paul-buerkner was this previously working? Even without the recent edits I made to the vignette I couldn't run that part without errors.

**Comment by MansMeg** [comment]
Well spotted! 

I did not include any test for the rstan API so there is no check that the API hasn't changed. My guess is therefore that there must be a change in the rstan. Do you know if there are tests for the rstan optimize API?

I think all three of us tested the code. I, @avehtari, and @paul-buerkner, so my guess is that it is some change of the API that occurred since June this year.

**Comment by jgabry** [comment]
Ok I think I figured it out. The argument `importance_resampling = TRUE` is missing but is required when running `rstan::optimizing()` in order to get the `log_p` and `log_g` values. I'm not sure if it's supposed to be required or not (@avehtari ?), but currently it doesn't work without it. Either way the documentation for `rstan::optimizing()` is wrong because it says you get `log_p` and `log_g` when `draws>0` but doesn't mention requiring `importance_resampling=TRUE`.

**Comment by MansMeg** [comment]
That sound reasonable.  This did work before:
```
opt_independent <- rstan::optimizing(stm, data = lm_indep_post, draws = 5000, constrained = FALSE, hessian = TRUE, seed = 4711)
opt_correlated <- rstan::optimizing(stm, data = lm_indep_post, draws = 5000, constrained = FALSE, hessian = TRUE, seed = 4711)
```

**Comment by avehtari** [comment]
Ah, it was one of those Andrew's big data examples where I needed to have the faster option which is not computing log_p as it can take quite much time and not always needed it's useful to have that option. Currently, log_p is computed only if importance_sampling=TRUE, but we could make another option to decide when to compute log_p independently from option importance_sampling.
What do you think?

**Comment by jgabry** [comment]
Either way is ok with me. Whatever we decide we should update the doc accordingly.

**Comment by jgabry** [comment]
I'm going to fix the doc in rstan so it says that it only returns them if importance_resampling is TRUE, but we can still change it. I just want the doc to be current.

**Comment by jgabry** [comment]
I'm going to close this since the vignette works now that we added importance_resampling=TRUE.
