### ISSUE TITLE
Convenience functions for accessing pointwise estimates

### ISSUE THREAD

**Issue by jgabry** [stan-dev/loo#126]
Right now to get the pointwise values for elpd_loo, p_loo, etc., you have to do this: 

```r
object$pointwise[, "elpd_loo"]
```

but it would be nice if we offered a convenience function for this, e.g., 

```r
pointwise(object, "elpd")
```
which would return a vector of pointwise elpd values.

**Comment by MansMeg** [comment]
Yes! That would be good also for subsampling_loo.

**Comment by jgabry** [comment]
This ended up being useful for me for something so I will make a PR
