### ISSUE TITLE
large data vingette missing links to two references

### ISSUE THREAD

**Issue by avehtari** [stan-dev/loo#132]
The vignette 
http://mc-stan.org/loo/articles/loo2-large-data.html
lists
- Magnusson, M., Riis Andersen, M., Jonasson, J. and Vehtari, A. (2019). Leave-One-Out Cross-Validation for Model Comparison in Large Data.
- Magnusson, M., Riis Andersen, M., Jonasson, J. and Vehtari, A. (2019). Leave-One-Out Cross-Validation for Large Data. In International Conference on Machine Learning

but there are no links to the papers. 

Add links to these papers.

**Comment by avehtari** [comment]
Fix also typo
- [ ] approximatations -> approximations

**Comment by MansMeg** [comment]
Will fix. Is it ok to wait til after 6th of Jan when we know if we are accepted to AISTATS?
