### ISSUE TITLE
Clarify SE calculation for elpd_diff/elpd

### ISSUE THREAD

**Issue by fukayak** [stan-dev/loo#133]
I looked up the source code of `loo_compare` function and found that the `se_elpd_diff` function used in it multiplies SD of the difference of elpd of each observation by a square root of the number of observations (`sqrt(N)`).

As a result, the SE of the elpd difference increases as `N` increases. Instead, to obtain SE, the SD should be divided by `sqrt(N)`? (Or, am I missing something?) Thanks so much.

**Comment by avehtari** [comment]
`elpd` (and `elpd_diff`) is defined as a sum of N individual elpd (elpd_diff) values. For sum we need to multiply by sqrt(N). If you are interested in a mean of N individual elpd values then divide`elpd` and SE by N (sqrt(N)/N = 1/sqrt(N)).

This starts to be FAQ, so I think we need to add a comment to the code reminding that we are looking at sum. Reason for using sum is that then it's on the same scale as `p_loo` making certain comparison in the reported output easier for humans.

**Comment by MansMeg** [comment]
Sure. I can fix this thing when I fix the missing links.

**Comment by avehtari** [comment]
This is actually already mentioned in `loo-glossary`:
```
#' @section Standard error of `elpd_loo`:
#'
#' As `elpd_loo` is defined as the sum of N independent components (Eq 4 in
#' VGG2017a), we can compute the standard error by using the standard deviation
#' of the N components and multiplying by `sqrt(N)` (Eq 23 in VGG2017a).
```
but for those people who like to read the code instead of documentation, it's good to add a comment next to the specific line.

**Comment by avehtari** [comment]
Comment added (forgot to add issue number to the commit)

**Comment by fukayak** [comment]
I have to apologize for my inattention. Thank you very much for the prompt follow-up.
