### ISSUE TITLE
Where to include Aki's CV FAQ page?

### ISSUE THREAD

**Issue by jgabry** [stan-dev/loo#143]
A few questions:

* Where is the best place for the loo package to link to @avehtari 's [CV FAQ](https://avehtari.github.io/modelselection/CV-FAQ.html)? Should it be included like a vignette? Just linked to from the doc somewhere?

* Also, is there overlap between the loo glossary page (https://mc-stan.org/loo/reference/loo-glossary.html) and the CV FAQ? If so, should they be combined into a single document?

**Comment by avehtari** [comment]
Currently CV-FAQ sites LOO Glossary. Part of the CV-FAQ is bit more speculative than I would like to have in official documentation, but I could also clarify more which parts need more research.
