### ISSUE TITLE
Next loo release?

### ISSUE THREAD

**Issue by jgabry** [stan-dev/loo#144]
@avehtari @paul-buerkner @MansMeg @topipa Are we ready for a loo release? I think we still need to release Topi's stuff that got merged a few months ago, but are there other things any of you wanted to make sure we included in the next release?

**Comment by paul-buerkner** [comment]
Fine for me.

**Comment by avehtari** [comment]
I think I updated some references recently? Should be fine to make a release. The other utility/loss functions vignette will be delayed at least few weeks more.

**Comment by MansMeg** [comment]
I dont have anything new.

**Comment by topipa** [comment]
I updated the moment matching reference in PR https://github.com/stan-dev/loo/pull/145 . After that I don't have anything to add at the moment

**Comment by avehtari** [comment]
I noticed some issues we could fix
#106
#112
#116
#137

**Comment by avehtari** [comment]
I made PRs for #112 and #116

**Comment by jgabry** [comment]
@paul-buerkner Are there any updates we need to make to the LFO or non-factorizable vignettes?

**Comment by paul-buerkner** [comment]
I think so, yes. Good point. I will update them over the weekend or on monday.

**Comment by jgabry** [comment]
Ok cool, thanks

**Comment by jgabry** [comment]
I submitted loo to CRAN. Will close this issue once it's accepted.

**Comment by jgabry** [comment]
loo v2.3.0 is now on CRAN. I will tag the release and update the website.
