### ISSUE TITLE
'compare' is deprecated.

### ISSUE THREAD

**Issue by jjandshi** [stan-dev/loo#150]
In another package which depends on loo.
I got this error information: "Warning message: 'compare' is deprecated. Use 'loo_compare' instead.
How could I use the new loo_compare function, or use the old "compare" function? 
Thanks,

**Comment by jgabry** [comment]
Hi @jjandshi, I just notice nobody every responded to this issue, sorry!! You can safely ignore that warning message, but eventually that package that depends on loo should switch internally to using the newer `loo_compare()` function to avoid the deprecation warning.
