### ISSUE TITLE
documentation: likelihood vs. log-likelihood in relative_eff.function

### ISSUE THREAD

**Issue by psadil** [stan-dev/loo#156]
The documentation for `relative_eff` says that 

> * For use with the  `loo()`  function, the values in  `x`  (or generated by  `x` , if a function) should be  **likelihood**  values (i.e.,  `exp(log_lik)` ), not on the log scale.

But it also says, in the **Methods (by class)** section, that the function should output the log-likelihood:

> `function` : A function  `f()`  that takes arguments  `data_i`  and  `draws`  and returns a vector containing the log-likelihood for a single observation  `i`  evaluated at each posterior draw. [...including a few other references to log-likelihood...]

Shouldn't the second one also ask for a likelihood?

**Comment by jgabry** [comment]
Thanks for reporting this. I think you're right that the second one should also say likelihood instead of log-likelihood. Marking this as a bug so we make sure to prioritize correcting it in the next release.
