### ISSUE TITLE
Items for next release?

### ISSUE THREAD

**Issue by jgabry** [stan-dev/loo#160]
We have a bugfix for relative_eff for Windows users that we should release and we also have the new elpd() function and vignette, so I was thinking about doing another CRAN release sometime soon. 

Does anyone have anything else they would like to get in before we do another release?

**Comment by bnicenboim** [comment]
Hey, maybe it could be released? I'm using the new functions in the code of a new paper already, it would nice to have them in CRAN.

**Comment by jgabry** [comment]
@avehtari @paul-buerkner @MansMeg @topipa Do any of you have any bug fixes or anything else you definitely want to get in for the next release? If I don't hear anything in the next few days I'll assume we're good to go for a release.

**Comment by paul-buerkner** [comment]
I don't have anything right now.

Am Mi., 25. Nov. 2020 um 22:14 Uhr schrieb Jonah Gabry <
notifications@github.com>:

**Comment by rok-cesnovar** [comment]
I would hold off until we settle what is behind https://github.com/stan-dev/posterior/issues/101

**Comment by avehtari** [comment]
I don't have anything that couldn't wait for the next release after this. It would be good to fix that posterior object issue for this release.

**Comment by jgabry** [comment]
> I would hold off until we settle what is behind [stan-dev/posterior#101](https://github.com/stan-dev/posterior/issues/101)

I agree we should wait for that to be resolved. I think it's fixed by #161 in combination with https://github.com/stan-dev/posterior/pull/102, but I need to make another change or two to https://github.com/stan-dev/posterior/pull/102 before we merge it. I will try to do that soon.

**Comment by jgabry** [comment]
I've started preparing the release on the loo-v2.4.0 branch

**Comment by avehtari** [comment]
I have one minor issue that would be good to be fixed, just creating it

**Comment by avehtari** [comment]
"Using Leave-one-out cross-validation for large data" vignette has some issues that I think should be easy to fix, see #161 
These issues were just reported by one of my course students

**Comment by jgabry** [comment]
Ok thanks yeah let's fix those first

**Comment by jgabry** [comment]
Unfortunately I've now run into a new issue and we can't release until it's sorted out: the vignettes that use RStan are all crashing on my computer. Not sure what's going on but we'll see if Ben knows: https://github.com/stan-dev/rstan/issues/879

**Comment by jgabry** [comment]
@bnicenboim I'm getting an error running the elpd vignette. I think here 

https://github.com/stan-dev/loo/blob/4b3139d9d6800e51271636301b1083740b39f29a/vignettes/elpd.Rmd#L194

`log_pd` should be `log_pd_kfold`, right? I already fixed this on the branch for the 2.24 release so you don't need to change anything, but can you confirm this?

**Comment by bnicenboim** [comment]
yes! sorry about that

**Comment by jgabry** [comment]
No problem! Thanks for confirming.

**Comment by jgabry** [comment]
Ok I think all the issues have been sorted out. I'm going to go ahead and submit to CRAN. I will tag the release and update the website once it's accepted on CRAN.

**Comment by jgabry** [comment]
It's on CRAN now and I updated the website. @bnicenboim here's the url for your vignette https://mc-stan.org/loo/articles/loo2-elpd.html
