### ISSUE TITLE
Fixes for vignette "Using Leave-one-out cross-validation for large data"

### ISSUE THREAD

**Issue by avehtari** [stan-dev/loo#162]
The problems in the  "Using Leave-one-out cross-validation for large data" vignette were reported by one of my course students

- [x] move `library(loo)` before calling `loo_i`
- [x] fix `loo_i` so that it computes `r_eff` as currently
`loo_i(1, llfun_logistic, data = stan_df_1, draws = parameter_draws_1)` warns
```
Warning message:
Relative effective sample sizes ('r_eff' argument) not specified. PSIS n_eff will not be adjusted based on MCMC n_eff. 
```
which is confusing for new users.
- [x] fix `loo_subsample` so that it computes `r_eff` as currently it warns
```
`Warning messages:
1: Relative effective sample sizes ('r_eff' argument) not specified.
For models fit with MCMC, the reported PSIS effective sample sizes and 
MCSE estimates will be over-optimistic. 
2: Relative effective sample sizes ('r_eff' argument) not specified.
For models fit with MCMC, the reported PSIS effective sample sizes and 
MCSE estimates will be over-optimistic. 
```
which is confusing for new users.

**Comment by jgabry** [comment]
We should fix these on the branch loo-v2.4.0 because I'm slightly renaming some of the vignette filenames already so we can avoid clashes by working on that branch

**Comment by jgabry** [comment]
I can make these fixes now

**Comment by jgabry** [comment]
Ok these should be fixed now by https://github.com/stan-dev/loo/commit/b28dddeefeda0d762c6bdb5652a2c29ca5c5af13 and https://github.com/stan-dev/loo/commit/26458ac71d60d477ccd5de7954d4cf90be228570

**Comment by jgabry** [comment]
Because `relative_eff()` wants a likelihood function and not a log-likelihood function I added an argument to the log-likelihood function used in the vignette that allows turning on and off taking the logarithm. That seemed preferable to creating a separate function.

**Comment by MansMeg** [comment]
Wow! You're quick @jgabry ! Thanks for this!

**Comment by jgabry** [comment]
No problem, I was in the middle of working on loo stuff anyway! Do the changes look okay to you?

**Comment by MansMeg** [comment]
It looks great!

**Comment by jgabry** [comment]
Ok great, thanks for checking. Will close this issue now
