### ISSUE TITLE
Confusing documentation for loo_subsampling when using approximate posterior

### ISSUE THREAD

**Issue by kdubovikov** [stan-dev/loo#170]
As discussed in https://discourse.mc-stan.org/t/problem-running-loo-subsample-with-variational-inference-and-cmdstanr/22506/13

Documentation for the `loo_approximate_posterior` and `loo_subsample` says:

> draws : An object containing the posterior draws for any parameters needed to compute the pointwise log-likelihood. Unlike data , which is indexed by observation, for each observation the entire object draws will be passed to the draws argument of the log-likelihood function.

But when using `log_p` and `log_g` we are not guaranteed that draws argument will have the same dimensions for each call of the likelihood function.

**Comment by jgabry** [comment]
Thanks for reporting this. @kdubovikov or @MansMeg what do you think the doc should say here that would make the behavior clear?

**Comment by MansMeg** [comment]
I think we just need to explain the two-step behaviour of loo_subsampling(). I can fix this with a PR.

**Comment by jgabry** [comment]
Great, thanks!

**Comment by MansMeg** [comment]
Is this better @kdubovikov ?

https://github.com/stan-dev/loo/pull/176

**Comment by MansMeg** [comment]
I think this can be closed now.
