### ISSUE TITLE
moment_match = TRUE with cmdstanr ?

### ISSUE THREAD

**Issue by aaelony-catasys** [stan-dev/loo#182]
I ran a few `brms` models with `backend = "cmdstanr"` and wanted to compare models with `loo`.

`loo` runs with a warning: 

```
It is recommended to set 'moment_match = TRUE' in order to perform moment matching for problematic observations.  
```

Heeding the warning's advice suggests that I need to re-run with `rstan` as a backend.

```r
> loo(fit2, fit, moment_match = TRUE)
Error: Backend 'rstan' is required for this method.
```

Perhaps in the future `cmdstanr` might be supported without needing to rely on `rstan`?

**Comment by paul-buerkner** [comment]
the brms dev version from github already supports it I think.

aaelony-catasys ***@***.***> schrieb am Mo., 26. Juli 2021,
21:33:

**Comment by aaelony-catasys** [comment]
Nice. Okay to close if true. Thank-you.

**Comment by avehtari** [comment]
@paul-buerkner checking the current status and whether we can close this issue?

**Comment by paul-buerkner** [comment]
Can be closed I think.

Aki Vehtari ***@***.***> schrieb am Fr., 24. März 2023, 15:14:
