### ISSUE TITLE
A wrong link in a vignette

### ISSUE THREAD

**Issue by avehtari** [stan-dev/loo#189]
@yannmclatchie noticed
> on the vignette *Writing Stan programs for use with the loo package*, the link to the Pareto smoothed importance sampling paper points towards the wrong arXiv page (all links currently point toward the *Practical Bayesian model evaluation using leave-one-out cross-validation and WAIC paper*.

**Comment by MansMeg** [comment]
Fixed in PR #190

**Comment by MansMeg** [comment]
Small issue... Procrastinated instead of grading assignments. =)

**Comment by jgabry** [comment]
Thanks!
