### ISSUE TITLE
possible typo in LFO-CV vignette

### ISSUE THREAD

**Issue by copernican** [stan-dev/loo#243]
In the "Approximate $M$-step-ahead predictions" section of the LFO-CV vignette, there is an [assignment](https://github.com/stan-dev/loo/blob/dab6e58df6b5550ab9f87efc509192e2c204c345/vignettes/loo2-lfo.Rmd#L551)

```r
approx_elpds_1sap[L + 1] <- log_mean_exp(loglikm)
```

Should this assignment instead be `approx_elpds_4sap`?

**Comment by jgabry** [comment]
I think you're right, thank you for pointing this out! I just made a PR to fix it: https://github.com/stan-dev/loo/pull/244
