### ISSUE TITLE
Inconsistent documentation for `k_threshold` in `loo_moment_match()`?

### ISSUE THREAD

**Issue by kthayashi** [stan-dev/loo#275]
Apologies for opening two issues in a row. I think there may be a small inconsistency in the documentation for the `k_threshold` used by `loo_moment_match()` between the function documentation and moment matching vignette.

Function documentation:
https://github.com/stan-dev/loo/blob/6e7001e35bf74f9829ba9ab0618c1e860c7d7d94/R/loo_moment_matching.R#L28-L30

Vignette:
https://github.com/stan-dev/loo/blob/6e7001e35bf74f9829ba9ab0618c1e860c7d7d94/vignettes/loo2-moment-matching.Rmd#L169-L171

Should the function documentation be updated to say that the default value is `min(1 - 1 / log10(S), 0.7)`?

**Comment by jgabry** [comment]
Yes, thank you for pointing this out! The vignette is correct about the current default, so the function documentation needs to be updated.
