### ISSUE TITLE
Getting NA result

### ISSUE THREAD

**Issue by tortarantola** [stan-dev/loo#31]
Hi, I'm running LOO on log-likelihood matrices from two very similar Stan models with the same number of samples and data points, and one of them is returning NA results. I don't see any obvious differences between the matrices (neither have any zeros or NaN's). Any clue why this might be the case? Happy to transfer the two matrices but they're about 500MB each. 

> Computed from 4000 by 18600 log-likelihood matrix
> 
>Estimate SE
> elpd_loo       NA NA
> p_loo          NA NA
> looic          NA NA

**Comment by tortarantola** [comment]
Hi Jonah, there weren't any warning messages, but yes, there's one row in the pointwise matrix that has NA for the three values. I'm guessing that's the issue -- do you know what might cause this or how I could get around it?

**Comment by jgabry** [comment]
Hi Tor, I know you said the log-likelihood matrix is huge, but can you
share just the column in the log-likelihood matrix that corresponds to the
row with NAs in in the pointwise matrix? The rows should be in the same
order as the columns in the log-likelihood matrix you used.

I bet something is happening with the computations on that column that's
not triggering an error or warning for some reason.

Jonah

**Comment by tortarantola** [comment]
Hi Jonah, so it looks like the problem might be a weird distribution in the likelihood estimates for that data point. Below are the same data point for the model that doesn't work (returns an NA) and a similar model that does. Also attaching the columns.
[works.txt](https://github.com/stan-dev/loo/files/341582/works.txt)
[doesnt_work.txt](https://github.com/stan-dev/loo/files/341583/doesnt_work.txt)



![doesnt_work](https://cloud.githubusercontent.com/assets/7543663/16490445/99ff0b40-3ed1-11e6-8b67-7b6ac7385027.png)

![works](https://cloud.githubusercontent.com/assets/7543663/16490446/9a126cc6-3ed1-11e6-941c-f8a8f2210e75.png)

**Comment by jgabry** [comment]
Hi Tor, I responded over on the stan-users list, but I'll post it here too. 

The problem is that there is zero variance in the tail, i.e. all the values in the tail are the same. To see this you can do this in R: 

```r,
    log_lik <- read.delim("doesnt_work.txt", header=FALSE)[, 2]
    log_weights <- -1 * log_lik
    x <- log_weights - max(log_weights)   
    cutoff <- quantile(x, 0.8)  # find where the tail (20% largest values) starts
    print(x[x > cutoff])
```

**Comment by jgabry** [comment]
@avehtari currently we don't throw a warning or error for this. Aki, what do you think we should do in this case?

**Comment by avehtari** [comment]
If all the values in the tail are same then Pareto estimate does not work. Since Stan supports only continuous parameters, this kind of sample sets are suspicious and some warning or error should be given. Stan language allows building models with piecewise constant log density, which would have discrete set of posterior density values, but HMC is not able to sample from such distributions, and I cannot come up with any sensible case where the behavior as shown in the plot would be sensible in Stan. If we want to support loo package to be used with other software having sampling for discrete parameters, then simple choice in this kind of case would be return TIS-LOO result instead of PSIS-LOO result.

**Comment by jgabry** [comment]
On Saturday, July 9, 2016, Aki Vehtari <notifications@github.com> wrote:

> If we want to support loo package to be used with other software having
> sampling for discrete parameters, then simple choice in this kind of case
> would be return TIS-LOO result instead of PSIS-LOO result.
>
Ok great, that's exactly what I already tentatively changed it to do in
response to this. I'll put it in the next release.
>
>
