### ISSUE TITLE
Checking for rstan_options seems unnecessary

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/loo#40]
Why does https://github.com/stan-dev/loo/blob/master/R/extract_log_lik.R#L45 check for the existence of `rstan_options`? This causes an error in hBayesDM. If I just define

`rstan_options <- function(...) stop("should not have been called")`

`loo()` works.

**Comment by jgabry** [comment]
Not sure why it was that way, but I just changed it. Definitely unnecessary, but why was it causing an error?

**Comment by bgoodri** [comment]
If you try to put rstan in Imports rather than Depends but don't import
rstan_options.
