### ISSUE TITLE
k-fold-cv helper functions

### ISSUE THREAD

**Issue by bnicenboim** [stan-dev/loo#49]
Adapt helper functions [from here](http://htmlpreview.github.io/?https://github.com/stan-dev/stancon_talks/blob/master/2017/Contributed-Talks/07_nicenboim/kfold.html) to deal with k-fold CV.  (See also #25).

The user should add to the data declaration a vector that indicates which observations go to training (`trainidx`).

And the models should look like this:
```
model {
...
for (n in trainidx) 
      target += model_lpdf[n];
}
```

and some models could be written simply as

```
model {
...
y[trainidx] ~ normal(mu, sigma);
}
```

And the generative quantities has a `vector[N_obs] log_lik`. My helper functions extract the relevant log_lik, and calculate the elpd like it is done with loo.

**Comment by avehtari** [comment]
Thanks! Your case study looks great, and this kind of approach would be useful to add to the package.

**Comment by jgabry** [comment]
Following up on this finally! To start with we'll have the following options for a helper function that prepares data subsets for K-fold CV:

* [ ] Random permutation (ok when exchangeable, i.e. when LOO ok but N is big or k-hat is big)
* [ ] Balanced division based on outcome variable (e.g. if we have binary outcome with not so many obs in one of the categories then a random permutation can result in separation)
* [ ] Stratification based on discrete covariate(s)

**Comment by avehtari** [comment]
I comment here although implementation goes to rstanarm. `kfold` in rstanarm should accept the index array from these functions.

**Comment by jgabry** [comment]
Yeah, this is related to https://github.com/stan-dev/rstanarm/issues/228

**Comment by avehtari** [comment]
It seems there is a need also for kfold splits for time series. I don't know what what would a good shorter name for `kfold_split_m_step_ahead-prediction`? Maybe `kfold_split_timeseries', with options for how many steps ahead and a gap steps (which could be infinite for not including anything after the prediction steps).

**Comment by jgabry** [comment]
For the observations that are not in the testing set and also not in the training set (which depends on tuning parameters), should we go with `NA`?

**Comment by avehtari** [comment]
- [ ] It seems our kfold helper function names don't match with https://scikit-learn.org/stable/modules/cross_validation.html and it's likely to be my mistake. We should fix these to follow what they have (they have also nice figs)
- [ ] the current balanced allows only binary x, but it would be useful to allow any categorical x

ping @jgabry
