### ISSUE TITLE
PSIS improvements

### ISSUE THREAD

**Issue by jgabry** [stan-dev/loo#50]
## Brief description

The new and improved PSIS will take into account the MCMC effective sample size, fit the GPD using tail portion ->0, uses weakly informative prior for GPD, and
provides effective sample size and variance estimates that are easier to interpret 
than khat values. Updated paper https://arxiv.org/abs/1507.02646. Implementation details below.

The `new-psis` branch has some preliminary work on implementing these changes but it is not ready yet. 

## Implementation checklist

* [x] computation of relative MCMC efficiency for `exp(log_lik)`
* [x] new number of weights in tail for GPD fit
* [x] weakly informative prior for `k`
* [x] generic effective sample estimate for PSIS
* [x] variance of the expected loo predictive density `var(exp(loo_i))=var(epd_i)`
* [x] variance of the expected loo *log* predictive density `var(loo_i)=var(elpd_i)`
* [ ] variance of other functions (e.g. when using `E_loo`)
* [x] khat of other functions (e.g. when using `E_loo`)
* [x] update documentation

## Details

NOTE: the code snippets below are Matlabish pseudocode, where some
variables are vectors and broadcasting operators are assumed. Art
Owen's book chapter http://statweb.stanford.edu/~owen/mc/Ch-var-is.pdf
also has most of the equations, which should be relatively straightforward to 
implement in R.

<br>

* Relative effective sample size of `exp(log_lik)` from MCMC with the
usual algorithm. We could use use `neff` for `log_lik`, but `neff` for `exp(log_lik)` 
is better for the normalization term in self normalized IS.

```r
rel_neff = mcmc_neff(exp(log_lik)) / S
```

* The number of weights used to fit the generalized Pareto distribution is now
   decreasing with the number of draws S, and is also adjusted based
   on the MCMC `neff` for `exp(log_lik)`. This will answer the questions about
   the asymptotic properties, works better for thick tailed proposal
   distributions, and is adjusted based on dependent samples in Markov
   chain. The number of weights used to fit the GPD is now `3*sqrt(S)` but
   adjusted with relative effective sample size of MCMC, and no more than 20% of weights:

```r
n_pareto = ceil(min(0.2 * S, 3 * sqrt(S) / rel_neff))
```

* The Pareto fit uses a prior for k. This will stabilize estimates for very small 
Monte Carlo sample sizes and low neff cases. The weakly informative prior for 
the generalized Pareto distribution fit is a Gaussian prior centered on `kprior=0.5`. 
After computing `khat`, adjust it as follows:

```r
a = 10
khat = khat * n / (n + a) + a * 0.5 / (n + a)
```

* Generic effective sample size for PSIS:
   - `w` denotes the normalized Pareto smoothed weights
   - the first part is the usual estimate which is accurate for `k < 0.7`
  - `rel_neff` is the relative effective sample size of MCMC from above

```r
neff_psis = 1. / sum(w.^2) * rel_neff;
```

* E[epd_i]
  - `w` denotes the normalized Pareto smoothed weights

`E[epd_i] = sum(exp(log_lik) .* w)`

* Variance of the expected loo predictive density `var(exp(loo_i))=var(epd_i)`
(this is not for the expected loo *log* predictive density)
  - `w` denotes the normalized Pareto smoothed weights
  - `rel_neff` is the relative effective sample size of MCMC
  - This is based on eq 9.9 in http://statweb.stanford.edu/~owen/mc/Ch-var-is.pdf

```
var_epd_i = sum(w.^2.*(exp(log_lik)-E[epd_i]).^2);
```
* In order to get the variance of the expected loo *log* predictive density
`var(loo_i)=var(elpd_i)`, we need to project the distribution of `epd_i` through
log transform. We probably should do this with quadrature, but I quickly computed 
by sampling from the Gaussian and taking the logarithm.
  - with the addition of dividing by `rel_neff`
```r
z ~ N(E[epd_i], var[epd_i])
var(elpd_i) = var(log(z))/rel_neff;
```

* Total variance for elpd=sum(elpd_i). Square root of this could be reported to users as the Monte Carlo error estimate (which is reliable only if all k<0.7)

```r
var(elpd) = sum_i(var(elpd_i))
```

* For variance of other functions (e.g. when using `E_loo`), use equation
9.9 in http://statweb.stanford.edu/~owen/mc/Ch-var-is.pdf and divide
by `rel_neff` (the relative effective sample size of MCMC). For example,
for the predictive mean `mu`

```r
var_epd_i = sum(w. ^ 2. * (mu - sum(w. * mu)).^2) / rel_neff;
```
* khat estimate for other functions (e.g. when using `E_loo`). Compute function specific khat using (see Epifani et al (2008) ofr justification), where h is the function and w are raw weights.
```r
sqrt(1+h(theta)^2).*w(theta)
```

**Comment by jgabry** [comment]
@avehtari One thing that occurs to me about the effective sample size calculations is that in order for the loo package to compute `mcmc_neff(exp(log_lik))` we will need to have the log likelihood draws separated by chain. Right now the whole package is based on the user passing in an `S x N` log-likelihood matrix, but in order to calculate neff I think we would need them to pass in an `S/C x C x N` array or something like that, right? I suppose we could assume that the draws in the log lik matrix are ordered in such a way that we could internally separate the matrix into separate chains instead of requiring the user to pass in a 3-D array, but that seems a bit dangerous. 

To require the user to pass in a 3-D array instead of a matrix would be a pretty big break in backwards compatibility, but I guess that's ok if we call the next version of the package Version 2.0.  

What do you think?

**Comment by avehtari** [comment]
Oh, we are suffering because of permute=TRUE again...
I think we could allow SxN, but give a warning that PSIS n_eff is not adjusted based on MCMC n_eff. The shape of 3-D array in the future Stan has been recently discussed in Discourse, and it would be good use the same order. What kind of object you would get now from RStan with permute=FALSE? I think we should allow several chains in a 2D matrix, only if chain id index vector is also given.

**Comment by jgabry** [comment]
On Sun, Aug 13, 2017 at 3:54 AM Aki Vehtari <notifications@github.com>
wrote:

> I think we could allow SxN, but give a warning that PSIS n_eff is not
> adjusted based on MCMC n_eff.
>

Maybe we do this but eventually deprecate it?

The shape of 3-D array in the future Stan has been recently discussed in
> Discourse, and it would be good use the same order.
>

Yeah definitely.

What kind of object you would get now from RStan with permute=FALSE?
>

Currently it's an iteration x chain x parameter array.

I think we should allow several chains in a 2D matrix, only if chain id
> index vector is also given.
>

If it's possible that the iterations are permuted we'd also need an
iteration id index! But if eventually we can assume they are in order yeah
we could just have a chain_id vector.

**Comment by jgabry** [comment]
I think to start I'm going to write the code assuming an S x N matrix where
the iterations are not permuted and the chains are stacked in order. Then I
can just add some internal helper functions to convert the other types of
input to that form. That way when rstan changes it will only be those
helper functions that need to be updated.

**Comment by avehtari** [comment]
Your plan is reasonable.

**Comment by jgabry** [comment]
@avehtari For the prior on k:

> After computing `khat`, adjust it as follows:
> 
> ```r
> a = 10
> khat = khat * n / (n + a) + a * 0.5 / (n + a)
> ```

it sounds like you mean fit the GPD exactly the same way as before (well, using a different number of tail samples) and then just adjust k after the fact. Is that right?

**Comment by jgabry** [comment]
Also what is `n` here? Does `n` = tail length used to fit GPD?

**Comment by jgabry** [comment]
Related to my previous question about `k`, since when fitting the GPD the estimate for `sigma` is 
```r
sigma <- -k / b_dot_w
```
should the new adjustment to `k` come before or after it is used to compute `sigma`?

**Comment by avehtari** [comment]
> it sounds like you mean fit the GPD exactly the same way as before (well, using a different number of tail samples) and then just adjust k after the fact. Is that right?

Yes

> Also what is n here? Does n = tail length used to fit GPD?

Yes

> should the new adjustment to k come before or after it is used to compute sigma?

After

**Comment by jgabry** [comment]
Ok great, thanks!

**Comment by jgabry** [comment]
@avehtari Here's an update on the progress: 

Because there are lots of changes and new information that gets passed between functions (e.g. relative effective sample sizes), I'm leaving the `psislw` function in its old form and working on a new `psis` function that will replace it. The new `psis` function will be a generic function that has methods for log-lik arrays, matrices, vectors, and functions:

```r
psis.array(x, wtrunc, cores)
psis.matrix(x, chain_id, wtrunc, cores) 
psis.vector(x, chain_id, wtrunc, cores) 
psis.function(x, args, wtrunc, cores) 
```
where `chain_id` is not needed if using the array method since the chains will be separate. (Note about R: function names like `psis.array` are how methods are defined internally but the user just needs to type `psis(x)` and it will use the appropriate method based on the type of `x`). 

The object returned by `psis` will be a list of class `"psis"` containing named components 

* `pareto_k` (vector of `k` estimates, or a scalar if only doing psis on a vector input)
* `n_eff` (vector of psis neff estimates, or a scalar if only doing psis on a vector input)
* `lw_smooth` (matrix of smoothed but _unnormalized_ log weights, or a vector if using a vector input)

The biggest difference is that the returned weights have not been normalized (more about that below). 

The object will also have some `attributes` that can be accessed internally by functions in the package:
 * `norm_const_log` (saved values of `colLogSumExps(lw_smooth)` that can be used later to normalize)
 *  `tail_len` (tail lengths used to fit GPD)
 *  `rel_n_eff` (saved relative effective sample sizes, which may be used later for variance calculations)

The reason I think the new `psis` should return unnormalized weights but also save the constants needed for normalizing them is that some of the new formulas require both types of weights. To make this easy there will be a `weights` function in the package that will have options `normalize` and `log`, both defaulting to TRUE: 

```r
# weights method for 'psis' objects
#  @param object The object returned by psis()
#  @param normalize Should the returned weights be normalized? 
#  @param log Should the weights be on the log scale? 
weights.psis <-
  function(object,
           ...,
           log = TRUE,
           normalize = TRUE) {
    out <- object[["lw_smooth"]] # unnormalized weights
    const <- attr(object, "norm_const_log") # precomputed colLogSumExp(lw)
    if (normalize)
      out <- sweep(out, 2, const)
    if (!log)
      out <- exp(out)

    return(out)
  }
```
So it will be easy to pick the kinds of weights that we need for various subsequent computations. 

What do you think about this design?

**Comment by avehtari** [comment]
Excellent! I like it.

**Comment by avehtari** [comment]
Oops, it seems var_epd_i equation might have an error. I'll need to verify which will take one or two days...

**Comment by jgabry** [comment]
No problem. I'll work on getting the code for the rest of it ready in the
meantime.

**Comment by avehtari** [comment]
The last var_epd_i with mu had an error, I though I had fixed already.
I also added total variance for elpd.
I still need to make some checks for the calibration, but hopefully have time to check these in next couple days.

**Comment by avehtari** [comment]
Forgot to mention that I edited the issue to have the correct equation

**Comment by jgabry** [comment]
Ok thanks!

**Comment by avehtari** [comment]
I noticed that 
`n_pareto = ceil(min(0.2 * S, 3 * sqrt(S) / rel_neff))`
should be
`n_pareto = ceil(min(0.2 * S, 3 * sqrt(S / rel_neff)))`

**Comment by jgabry** [comment]
Glad you noticed that!

**Comment by avehtari** [comment]
I added to the implementation list "khat estimate for other functions"

**Comment by jgabry** [comment]
Default if matrix is used but no `chain_id` is provided: warning that we're assuming independent draws instead of MCMC draws. And then set MCMC rel_n_eff to 1.

**Comment by jgabry** [comment]
Also we don't need to provide `wtrunc` argument anymore, so get rid of that.

**Comment by jgabry** [comment]
We should also allow MCMC effective sample sizes to be specified by the user to avoid computing them when possible. For example, we shouldn't need to compute MCMC ESS in loo when using an rstanarm model since the the MCMC ESS is already stored in the rstanarm fitted model object.

**Comment by jgabry** [comment]
New plan: 

- No chain_id argument to psis or loo
- Add r_eff argument that defaults to 1
- Expose helper function (that takes log_lik and a chain_id arg) for users to calculate r_eff if they want to pass it to the r_eff argument

**Comment by yao-yl** [comment]
Hi Johna,  Could you point me to what I can do for merging the stacking part?

**Comment by jgabry** [comment]
Also add column to k-hat table with minimum PSIS effective sample sizes, and also extend plot method to allow plotting psis effective sample sizes.

**Comment by jgabry** [comment]
* [ ] Add `save_psis` argument to `loo` to toggle whether or not to save the `psis` object inside the `loo` object
* [ ] Change `E_loo` to `E_psis` and accept `psis` object as input
* [ ] Compute `k_hat` for `E_loo`

**Comment by jgabry** [comment]
* [ ] Finish implementing mcse_elpd_loo for function method

**Comment by jgabry** [comment]
* [ ] Check that R and Matlab implementations give identical results

**Comment by jgabry** [comment]
I think we can finally close this!!
