### ISSUE TITLE
psislw uses too many cores

### ISSUE THREAD

**Issue by cfhammill** [stan-dev/loo#53]
psislw should honour `mc.cores` like rstan.

https://github.com/stan-dev/loo/blob/master/R/psislw.R#L40

Simple fix would be to replace the cores default with `getOption("mc.cores", 1)`

It's dangerous to use `parallel::detectCores()` by default, for example in multi-user environments.

**Comment by jgabry** [comment]
@cfhammill Thanks for this issue and sorry for not responding sooner. We made a change like this but I forgot to post here when we did that. 

I agree that the default shouldn't be detectCores. In loo v2.0.0 (currently being developed on the `new-psis` branch and to be released soon) the default has been changed to 1 core unless `getOption("loo.cores") > 1` or the `cores` argument is specified.

**Comment by cfhammill** [comment]
Thanks Jonah! Single core default makes a lot of sense. 

Curious though why the option should be `loo.cores` instead of `mc.cores`.

**Comment by jgabry** [comment]
Originally I thought it could be useful to control the number of cores used
by rstan and loo separately. But I’m not sure it’s actually of any real
benefit. So at this point it’s loo.cores to not break backwards
compatibility. But loo 2.0 is a major release so we could potentially make
the switch.

**Comment by cfhammill** [comment]
Seems like if a user wants that granularity (rstan vs. loo) they can pass a cores argument. If you wanted to deprecate `loo.cores`, I'd be happy to add code to check for `loo.cores` and `mc.cores`, giving `loo.cores` precedence but issuing a deprecation message.

**Comment by cfhammill** [comment]
Sure thing!

**Comment by jgabry** [comment]
Great. Thanks for taking the initiative on this.

**Comment by jgabry** [comment]
Closing now that #62 was merged. New release will be soon.
