### ISSUE TITLE
model_weights does not yet seem to work

### ISSUE THREAD

**Issue by paul-buerkner** [stan-dev/loo#55]
I recently updated to the dev version of loo 2.0 (new-psis branch) to prepare brms for its release. I also tried out the new `model_weights` function, which results in an error. Reproducible example:

```R
library(brms)
fit1 <- brm(rating ~ treat + period, data = inhaler)
fit2 <- brm(rating ~ treat + period + carry, data = inhaler)

ll1 <- log_lik(fit1)
ll2 <- log_lik(fit2)
loo::model_weights(list(ll1, ll2))

"Error in elpd_loo[k] <- L$elpd_loo : replacement has length zero"
```

**Comment by paul-buerkner** [comment]
Thanks that would be perfect!

**Comment by paul-buerkner** [comment]
Will `model_weights` and `model_select` be part of the loo 2.0 release? If yes, I would really appreciate you merging the latest version of these functions into the `new-psis` branch so that I can write wrappes around them for use with brmsfit objects.

**Comment by yao-yl** [comment]
Yes I believe it will be merged very soon...

**Comment by yao-yl** [comment]
I have made a pull request and model_weghts() will be there.
