### ISSUE TITLE
model_weights and model_select should not print inside the function

### ISSUE THREAD

**Issue by paul-buerkner** [stan-dev/loo#59]
If special printing is desired, such as the current

```
The stacking weights are:
Model 1 Model 2 
  xxx   xxx 
```

I suggest giving the output of `model_weights` and `model_select` a class and define a print method for these classes. This is cleaner than automatically printing within the function.

**Comment by yao-yl** [comment]
Hi Paul,
Thanks for the suggestion!  I will try to improve it.
Yuling

**Comment by jgabry** [comment]
I agree about not printing from inside the function. @yao-yl I recommend
what Paul suggested, i.e. we can give the output a specific class and
define a print method for that class.

**Comment by jgabry** [comment]
Actually @yao-yl, I have to make some code changes anyway, so I can take care of this. Don't worry about it.

**Comment by jgabry** [comment]
@yao-yl I cleaned up some code and doc and then changed the printing. I need to fix the tests, which will now fail after I changed some of the error message text, but I'll fix those soon.

**Comment by yao-yl** [comment]
Thanks!

2018-02-28 14:56 GMT-05:00 Jonah Gabry <notifications@github.com>:
