### ISSUE TITLE
model weights for k-fold cross-validation?

### ISSUE THREAD

**Issue by jgabry** [stan-dev/loo#70]
@avehtari @yao-yl Is using `stacking_weights` recommended also when `lpd_point` comes from K-fold cross validation?

**Comment by avehtari** [comment]
`pseudobma_weights` and `stacking_weights` should not care where `lpd_point` comes from, and thus K-fold-CV should work fine, too.

**Comment by jgabry** [comment]
Ok that’s what I thought but I didn’t see it mentioned in Yuling’s documentation. I’ll add a mention of that.
