### ISSUE TITLE
LOO fails for data with only one observation

### ISSUE THREAD

**Issue by paul-buerkner** [stan-dev/loo#71]
Reproducible example with the dev version of brms:

```R
fit1 <- brm(count ~ log_Age_c, epilepsy)
LOO(fit1, newdata = epilepsy[1, ])
> Error in colSums2(x) : 
>   Argument 'dim' must be an integer vector of length two. 
```

I think there is a `drop = FALSE` argument missing somewhere when indexing observations. If possible it would be amazing if this could be fixed before releasing loo 2.0.

**Comment by jgabry** [comment]
Thanks Paul, I’ll look into it before releasing.

**Comment by jgabry** [comment]
Should be fixed now. You had the correct diagnosis. (Just a heads up that the reported SEs are going to be NA in this case since they rely on a variance calculation.)

**Comment by paul-buerkner** [comment]
Thanks! I currently have this one-observation case in brms when I compute LOO for models with non-conditionally-independent observations such as for SAR models. I remember that Aki wrote something about how to split such dependent observations and produce a LOO SE regardless, but I can't remember where I have seen it.

**Comment by avehtari** [comment]
@paul-buerkner can you email me with details of that SAR model case? I can't remember the answer, but I guess I'll remember or figure it out when I see the details.

**Comment by paul-buerkner** [comment]
Sure, will do!
