### ISSUE TITLE
psis() with small log ratios 

### ISSUE THREAD

**Issue by yao-yl** [stan-dev/loo#73]
When the log ratio in psis() function is small, it seems it cannot return the correct log weights. A small log weights will (often) occur when dropping some constant in log probability computation.

For example:
```
log_ratios=rnorm(1000,-100, 1)
psis_weights=psis(log_ratios=log_ratios)$log_weights
```
Both psis and weights(psis) will return a constant log weight for each data point
```
> summary(psis1$log_weights)
       V1        
 Min.   :-97.24  
 1st Qu.:-97.24  
 Median :-97.24  
 Mean   :-97.24  
 3rd Qu.:-97.24  
 Max.   :-97.24  
> summary(weights(psis1,normalize=T))
       V1        
 Min.   :-6.908  
 1st Qu.:-6.908  
 Median :-6.908  
 Mean   :-6.908  
 3rd Qu.:-6.908  
 Max.   :-6.908  
```
This can be solved by first normalizing the log ratios
```
log_ratios=log_ratios-mean(log_ratios)
psis_weights=psis(log_ratios=log_ratios)$log_weights
```
```
>summary(psis_weights)
       V1         
 Min.   :-6.8539  
 1st Qu.:-4.2206  
 Median :-3.5175  
 Mean   :-3.5160  
 3rd Qu.:-2.8394  
 Max.   :-0.1453  
```
The k hat estimations are the same in these two cases. I suspect it is a numerical problem when doing exp and log.

**Comment by avehtari** [comment]
Instead of mean
```
log_ratios=log_ratios-mean(log_ratios)
```
better would be max
```
log_ratios=log_ratios-max(log_ratios)
```
as then the largest log ratio is always exactly 0, and the largest (unnormalized) ratio is 1. With mean it's still possible that max log ratio is far from 0. This is what my matlab-code does. It seems that this has been dropped from R code,

**Comment by jgabry** [comment]
I didn't remove this step from the R code on purpose but it does look like the new `psis` skips this step. I will fix it now.

**Comment by jgabry** [comment]
@avehtari @yao-yl Actually I never removed this step from the R code:

https://github.com/stan-dev/loo/blob/71d0d48800f90894a9b9b2d8bad7bd144ba49e4d/R/psis.R#L296

So I don't know why there's a problem. Any ideas?

**Comment by yao-yl** [comment]
I think the problem is the result of  truncation 
 https://github.com/stan-dev/loo/blob/71d0d48800f90894a9b9b2d8bad7bd144ba49e4d/R/psis.R#L223
Note that the pre-standardization is only done in do_psis_i(). So max_wts[n] in the last line the unnormalized version, which can be a tiny number, while the log_weights[, n] returned by do_psis_i() is normalized version. 

This  should be solved by taking the truncation into the do_psis_i() part.  Simply remove Line-223 and add  truncate_lw(lw_i, upper = 0 ) after line https://github.com/stan-dev/loo/blob/71d0d48800f90894a9b9b2d8bad7bd144ba49e4d/R/psis.R#L315
will work.

**Comment by jgabry** [comment]
Ok yeah that makes total sense. I will fix it.

**Comment by jgabry** [comment]
@yao-yl Just opened a pull request (#74) with a fix.  I think it's right, but always good to double check. can you take a quick look?

**Comment by jgabry** [comment]
in terms of the experiments for the PSIS paper, yeah many of them could maybe be favorably affected. For most practical examples it doesn’t change the results, and when it does it should make them better.

**Comment by yao-yl** [comment]
Yes, I agree.

**Comment by avehtari** [comment]
Great catch @yao-yl 

> in terms of the experiments for the PSIS paper, yeah many of them could maybe be favorably affected.

PSIS paper experiments were made with my m-code, which did the truncation before rescaling.
