### ISSUE TITLE
Problem installing loo from CRAN and GitHub

### ISSUE THREAD

**Issue by mjg4243** [stan-dev/loo#80]
Here is the error:

Error in namespaceExport(ns, exports) : 
  undefined exports: allValue, allocArray, allocMatrix, allocVector, anyMissing, anyValue, binCounts, binMeans, colAlls, colAnyMissings, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse, colCounts, colCummaxs, colCummins, colCumprods, colCumsums, colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs, colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats, colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds, colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads, colWeightedMeans, colWeightedMedians, colWeightedSds, colWeightedVars, count, diff2, indexByRow, iqr, iqrDiff, logSumExp, madDiff, mean2, meanOver, product, rowAlls, rowAnyMissings, rowAnyNAs, rowAnys, rowAvgsPerColSet, rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods, rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps, rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins, rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks, rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars, rowWeightedMads, rowWeightedMeans, rowWeightedMedians, rowWeightedSds, rowWeightedVars, sdDiff, signTabulate, sum2, sumOver, t_tx_OP_y, validateIndices, varDiff, weightedMad, weightedMean, weightedMedian, weightedSd, weightedVar, x_OP_y
ERROR: lazy loading failed for package ‘loo’

**Comment by jgabry** [comment]
Sorry you're getting an error. The problem here seems to be the __matrixStats__ package (all those function names in the error message are from that package). __matrixStats__ should get installed automatically with __loo__, but it seems like that's not working on your machine for some reason. What happens if you open a fresh R session and try installing __matrixStats__ on its own? 

```r
install.packages("matrixStats")
```

**Comment by mjg4243** [comment]
I did have MS already installed, but I think you are right in that there is a problem there -- I will reinstall and try again and let you know.
Thanks for responding so promptly.
Best regards
Mike Gallagher 

    On Tuesday, April 24, 2018, 11:44:02 AM CDT, Jonah Gabry <notifications@github.com> wrote:  
 
 
Sorry you're getting an error. The problem here seems to be the matrixStats package (all those function names in the error message are from that package). matrixStats should get installed automatically with loo, but it seems like that's not working on your machine for some reason. What happens if you open a fresh R session and try installing matrixStats on its own?
install.packages("matrixStats")

**Comment by mjg4243** [comment]
and that did it!  Thanks again
Mike Gallagher 

    On Tuesday, April 24, 2018, 11:44:02 AM CDT, Jonah Gabry <notifications@github.com> wrote:  
 
 
Sorry you're getting an error. The problem here seems to be the matrixStats package (all those function names in the error message are from that package). matrixStats should get installed automatically with loo, but it seems like that's not working on your machine for some reason. What happens if you open a fresh R session and try installing matrixStats on its own?
install.packages("matrixStats")
