### ISSUE TITLE
relative_eff uses slightly wrong algorithm

### ISSUE THREAD

**Issue by avehtari** [stan-dev/loo#85]
`relative_eff` computation in R has two problems: 
1. initial sequence truncation is based on individual lags, but should be based on pairs as in Stan
2. autocorrelations are used differently, which may be suboptimal compared to FFT version used in Stan

Fix
 - [x] use Geyer's initial monotone sequence as in Stan
 - [x] check that autocorrelation values match with code in Stan or change the code to use FFT

**Comment by jgabry** [comment]
When https://github.com/stan-dev/rstan/issues/525 is fixed we can use that
