### ISSUE TITLE
Faster loo estimate for large n using random sample loo

### ISSUE THREAD

**Issue by avehtari** [stan-dev/loo#87]
If n is large, computation of PSIS-LOO can take lot of time. But if n is large, it is likely that we can get a useful estimate by taking a random sample of m LOO folds to compute and estimate the population LOO using that sample. projpred package uses this approach to speed up variable selection part. This would especially useful in cases where log_lik is computed outside of Stan, as then log_lik is computed only for m<n of observations.

**Comment by aadler** [comment]
Wasn't loo going to have portions written in C++ for speed purposes?

**Comment by avehtari** [comment]
> Wasn't loo going to have portions written in C++ for speed purposes?

That is independent of this, and there is a separate issue #33 for that

**Comment by avehtari** [comment]
Ping @MansMeg

**Comment by jgabry** [comment]
Closing since we already merged #113 with `loo_subsample()`
