### ISSUE TITLE
Error Earlier when Models Aren't Comparable

### ISSUE THREAD

**Issue by billdenney** [stan-dev/loo#89]
I just tried to compare two `brms` models which accidentally had different numbers of observations due to a predictor being `NA`.

When using `loo` on the models, it computed everything for both models then gave the error "Models don't have the same number of data points".  It would be helpful if this error were tested for before doing the calculations so that the errors came immediately rather than after multiple, potentially long, calculations.

**Comment by yao-yl** [comment]
Hi, I think the current package counts and compares the number of observations in each model after one MCMC run, and before any LOO calculation.

Though it may be even more efficient to count sample size even before any other computation, I think the main change is the difficulty of finding sample size in a more complicated model, before Stan gets compiled.

**Comment by billdenney** [comment]
If it's infeasible/impossible, no worries and feel free to close the issue.  I hoped that the typical object passed in would have enough information to determine the number of observations.

**Comment by avehtari** [comment]
It would be helpful if you would attach the lines of code you used, but I'm guessing you had something like
```
loo(model1, model2)
```
If you had something like this then this is `brms` package issue and not `loo` package issue. `loo()` in `loo` package doesn't accept models as arguments, but `loo()` in `brms` package accepts (and I know it's not always obvious which package code is first called when overloading of function names is used in R) . Pinging @paul-buerkner

**Comment by paul-buerkner** [comment]
Yeah that's indeed a brms issue. Would you mind opening an issue on https://github.com/paul-buerkner/brms ?
