### ISSUE TITLE
Windows 10 parallelization can be super slow

### ISSUE THREAD

**Issue by avehtari** [stan-dev/loo#94]
Lawrence Hunsicker reported that Windows 10 is super slow in parallelization if `.rprofile` has `options(mc.cores = parallel::detectCores())`. The same line in a script is not a problem,
https://discourse.mc-stan.org/t/problem-parallelizing-rstanarm-loo/6433/10

I don't know what we can do for this in `loo` package, but I add this here if someone is hit by the same Windows bug.

**Comment by jgabry** [comment]
We could mention this in the package documentation, but if this is very severe then maybe it's worth printing a message about it to Windows users when the package is loaded?
I'm not sure what the message would be precisely, but it's possible by adding to the `.onAttach()` function. Currently it's this:

https://github.com/stan-dev/loo/blob/e147fd32987bbc619c96537c8f8e043febb4125d/R/zzz.R#L1-L10
